++++
<img align="left" role="left" src="https://camo.githubusercontent.com/5b298bf6b0596795602bd771c5bddbb963e83e0f/68747470733a2f2f692e696d6775722e636f6d2f7031527a586a512e706e67"/>
++++

= My home Kubernetes cluster :sailboat:

_... managed by Flux and serviced with RenovateBot :robot:_

++++
<br /><br /><br />
++++

== :book: Overview

This is repository declares the state of my home kubernetes cluster.

It is built off the link:https://github.com/k8s-at-home/template-cluster-k3s[k8s-at-home/template-cluster-k3s] repository.

Details on it's setup and initial configuration can be found on the link:https://doku.bergmann.click/k8s/[documentation site].

If you have any question feel free to open an link:https://github.com/bergmann-it/homepi-cluster/issues/new[issue] or link:https://github.com/bergmann-it/homepi-cluster/compare[pull request].

== :handshake: Thanks

All this is inspired by the people behind link:https://k8s-at-home.com/[k8s at home] and the clusters shared at link:https://github.com/k8s-at-home/awesome-home-kubernetes[awesome-home-kubernetes] or via  the link:https://github.com/topics/k8s-at-home[k8s-at-home topic].

== Initial setup

* `k3sup install --ssh-key ~/.config/ssh-ident/identities/personal/id_ed25519 --host 192.168.8.16 --k3s-extra-args="--disable servicelb --disable traefik" --ip 192.168.8.16 --k3s-version=v1.21.0+k3s1 --local-path ~/.config/kube/config`
* `flux check --pre`
* `kubectl create namespace flux-system`
* get secret key file 'sops.gpg' from 1password
* `kubectl create secret generic sops-gpg -n flux-system --from-file sops.asc=sops.gpg`
* `kubectl apply --kustomize=./cluster/base/flux-system`
