apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-default-cert
  namespace: traefik
spec:
  dnsNames:
    - k8s.bergmann.click
    - "*.k8s.bergmann.click"
  secretName: tls-wildcard-default
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: tls-wildcard-default

