apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - "${METALLB_LB_RANGE_V4}"
  - "${METALLB_LB_RANGE_V6}"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: ${AS_NUMBER}
  serviceExternalIPs:
  - cidr: ${METALLB_LB_RANGE_V4}
  - cidr: ${METALLB_LB_RANGE_V6}
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: edgerouter
spec:
  asNumber: ${AS_NUMBER}
  peerIP: ${ROUTER_IP}
