apiVersion: v1
kind: Secret
metadata:
    name: blescalesync-secret
    namespace: default
type: Opaque
data:
    passwd: ENC[AES256_GCM,data:9ow49umObqCQDh7En/NMs7sa9yegWpuD,iv:cKrBpFgqQpf5cZUVGm5Q8msHQdTeFlYetNaJKiObAJ8=,tag:TeGWB5aqpDbfBKSNzPiuGg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T14:55:38Z"
    mac: ENC[AES256_GCM,data:8+0MfoqutipMpSaSoQ4XNP9LwfMQJ8H8ihKQ+mzwVYSV5Cj5rcsZ7DbdFCtYT7mfyBS7086R8EntjwVqLh4VeeKDTzhiyJy0y0aPmRrm7QiOv7PvgEkhqtsnE8vCriX4MI8cTL2BEHE5UoREdWriryBNv1wZnc/Pgj3j1VCL0fE=,iv:7oN1HnUlc612Mq1ikhGWuHkjrvfXZZxXUAK5e43uFXc=,tag:eJ23ssZkU/fNpHRyawwYuQ==,type:str]
    pgp:
        - created_at: "2026-07-28T14:55:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/AQ//d/NXFrfC/Z0GlrYxqoqh9ARcmWRA7m9ubpYZMqr1JVSk
            oIsDO+gTWya4jD5t0X7jDswfgpQkT5pIoxkao4E+8wa4PC6JT2J85CWZKim1QWjJ
            UKfO+6eYNSfuXGuPNQHQsnX0YohAqPaYwAivjqZDjlHdlGmimSLrWe4dARykNvM+
            Rr34dC20ILBEw7WZ+bZ1YQh8q22PzhDbsys020K4giLKWqUFcWm1evJM93+wDfFL
            sAj4Gt+GVltIjoDURWun7mVVSx53Pa29hXPbk46+ELGOZ6zMNpIqBEnXndeAtB0/
            WHsFo38FRAHePB0nAeMKjVYcQb25mNVEUwm5jblc1Urj/LS/nkEgb53Q7Fid31l7
            0E3OOsUCoF1IbxIteExcNnQ462JeWqDUQGVnYnaqAR+6dvIAilrnGrXALNQ5ZGVh
            ctr8+WZB6vQgqwXra5rnMzB1ZtTaXgrliB89g0WBtZw+0b3ZIRsDBWHRJLRZymHL
            amNg8/dSlsF32s0Afwl30ly2aqoZ/bMLK3NQVONGhjB5W8i1euwZ2x4WW4mQLO9n
            aLAoi8/O3VOuKTRTVg/GjOiY0BwbSUxrDLT5VpAqCeckXzM0niltexg3GtMTH4fj
            gVeDjmVO4VMO/BXh6ua7zRJwBOdsCjiIAah/cvtLHYyHrUwepxz6ePehIkgKdq/S
            XAFr91MJg/wfK+iTe1Uq5ZFJmJs3rbnMN/9tBm1UD4givFceimD+gy0YQ2wZ8gVl
            cIUR3IeBhW1qs6x6/YcqucwvVObEUYq1jAb+vsEb0QlKE8k+ZrQCpEZAP55M
            =/LBe
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    version: 3.13.3
