apiVersion: v1
kind: Secret
metadata:
    name: blescale
    namespace: default
type: Opaque
data:
    passwd: ENC[AES256_GCM,data:rrCGZ0RZ8t2QpkyjMkO9LONTo7DCLDTt,iv:iBZt5eXDjPH8i8HawWBzhcOba5pRcs7g85GYQhSbC+I=,tag:4oLd4BFb5CLWcEtdja8lEw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T03:29:06Z"
    mac: ENC[AES256_GCM,data:AwVoR9Cu0Wj6Lz00fivgd2srp86th/NpXChQ5IIwAhsaW79Tl+ly2liI1bkSmkQThe7e3QwM2nPtfbQ1lhMOmpEG6sCLJAfDhVb5Vxhq/Xz7c8l6eehh8PCld94iW3sJlyJYADLh26cBYZO4FPomCMj8UTIeYr4pwB8R8iqi7yk=,iv:Mf5QO7KjMt/4siU2Pwlfz/DXtP0jlX6kEyVtU/lFW6c=,tag:rZk/p0Fv6MwMpnwZXAmeLA==,type:str]
    pgp:
        - created_at: "2026-07-27T03:29:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/ARAAhpVyw0Ieg/MHh90V6D1F37cCKiomhq8MZRHgZfgPXgaw
            w7ZiMa9draCIrCI3SmE8YZHupcUeAwXaiD1LWqA2PZpcZsTZze8TXv2PyX3Vg5MJ
            cvUQ6mGnXT98cv1ObKDIPlYCtaczoislo5P5k5/Oa7zUXRnWwR+u3c0MayVaKscs
            LnrefvJr4+66fSrc9IxDVudXgGbxTIj3EW35KhjD8gBTKKdNf7L3e2t2dtv9vRFp
            pyVGgMuOUik0M3Rrin2z7ncdkx0+/Y4mnm1YyA4STKK2AyMuOa1u7OK7ZGwJG+MZ
            TW3IFvsWZYEzKCqCbpTfQ85jV+6txZLQEii2HCgAqVL2VrJ8CigCAa2YvbewrBH8
            0uaMeHOfn29IN6gU4u0WqbT7xbXeu4apz/EncDsi6FPQOdwR+zt7nhV1v76lmgU4
            8ZyFmT2oqvwsBX6xrQVeTfMIEeHK7zbf9V9mBnUDCxdUTB+enbN1//plVnD0dzFI
            pZimnUaIhQYJbQZ7i305sxqQfpfO5nwes8dYJgYT8jmGsPUlcmWA7pUBfJEXtysn
            99668DVcksBo0skYxiTY5+x/ozn5mnJ7QnCP5XhDwjdrInR+WmC+4K7nKopJnnSI
            SzTjFxG8wCtyjrp8qN9sdrmBAI9fcHW72Vb/mVBQMhG62pHKA8zkebKSDg4QDl/S
            XgFG2GQxGN+bEzRI4X8y6oi8spHxcl4l2IBMvl1v8y/3sDn4x+kIXsU9ceeFR5Rk
            fOuPzHx0TCqcIBuEDbJVvbpQ0ZlS2JmsVOyUANwXnSMejQO031/96dF3NK81MPA=
            =2r8t
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    version: 3.13.2
