---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: k8sonlab-charts
        namespace: flux-system
  values:
    env:
      TZ: 'Europe/Berlin'
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: unifi.bergmann.click
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8443
      tls:
        - hosts:
          - wifi.bergmann.click
          secretName: wifi-cert
