---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 0.2.15
      sourceRef:
        kind: HelmRepository
        name: k8sonlab-charts
        namespace: flux-system
  values:
    env:
      TZ: 'Europe/Berlin'
    service:
      port: 443
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: unifi.bergmann.click
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - unifi.bergmann.click
          secretName: unifi-cert
    configVolume:
      storageClassName: "local-path"
