---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 13.0.10
      sourceRef:
        kind: HelmRepository
        name: truecharts-charts
        namespace: flux-system
  values:
    env:
      TZ: 'Europe/Berlin'
