---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    persistence:
      data:
        enabled: true
        mountPath: /unifi
        accessMode: ReadWriteOnce
        size: 1Gi
    env:
      TZ: 'Europe/Berlin'
    image:
      tag: '6.0.45'
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: unifi.bergmann.click
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: 8443
        tls:
          - hosts:
            - unifi.bergmann.click
            secretName: unifi-cert
      portal:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: wifi.bergmann.click
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: 8843
        tls:
          - hosts:
            - wifi.bergmann.click
            secretName: wifi-cert
    service:
      main:
        ports:
          portal-http:
            enabled: true
          portal-https:
            enabled: true
