---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: containeroo-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.containeroo.ch
  timeout: 2m
