---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openccu-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://openccu.github.io/OpenCCU
  timeout: 2m
