## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
    name: minio-creds-secret
    namespace: minio-s3
type: Opaque
data:
    #ENC[AES256_GCM,data:jUQn9siZ++wCtW/NEfKhEcvmxZ0uCDzopULK1G9DO4R6gclJk1j8PHRi0cfcYHPTwhB38W5awEr5BZYKnEObUD3s9trwbCfS,iv:mWEe9eRjIhq6evaI1+kgYMDfjENcp33yRsrKexYcSjM=,tag:wBKjyi8FZ9n+HcsIcOCusQ==,type:comment]
    accesskey: ENC[AES256_GCM,data:LuPi8XYysZ8=,iv:Yfz/ZaE6lH3nv/r2cJS/EBEWw5dM9gw8M4GsFjdtiGg=,tag:RWMQmwDWGuEDeT6XUDEJTg==,type:str]
    #ENC[AES256_GCM,data:i8m62+3Ylch6Qg6pHPmsBYJf1OFLe6rfbXyuHZ3M7Y+ZqN8gD/q05CMFIDpxiTi83d6pWdRlv+w88gnLwcW1NERD73d/00P8kFFi,iv:WrCjl9881lsAUwTvrGwz+hM8/LbLK8s3pMIWIT2ERxc=,tag:Axj4+4KSIFd8Wpxp83bzBg==,type:comment]
    secretkey: ENC[AES256_GCM,data:g80ZhxbY1c5qSH0BWo/VxAz27QMfnpUCJdQHUWuBBuYacRLjKDM4GsWlOwQ=,iv:0I9I4BAaR5MUtLsy9/5m2k+1DZhW1k0w6wJfQi02H3M=,tag:BOlwcr8JtJRYu2OlnPQIVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-14T18:49:37Z"
    mac: ENC[AES256_GCM,data:tggWCzBQRtFJoHX4rT7hNZsNGDVXc7koOh9OAJQ6Tfw8SoAZlj1GCOX8mWPWxdL4icbuHalbWM7aa3PWlGGzaCIEC0zBV7YUQYY5cwSp0jJW3AYfMDWjOLxk1K44n90Croou3gV+JHZKGz2PwNAXsnFfHaPksjI7Bns6yLRP7xg=,iv:lXAQUG2mg766rzEVg4CfZ1sLuQK7RSf+r0FsfvaDemA=,tag:l2pm6BEu2t1L4mep/ttlsw==,type:str]
    pgp:
        - created_at: "2021-05-14T18:49:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/AQ/+PTB0gzX3ArPloFzeNE1u4SseRo5KBQ0iVV/NCCUS+CmT
            36XeAOzeAe7ISIeiUmzzdsTSkBld9H3KEdP6m0o7GusRLyOaQSDzSBLc4DtGfBKD
            3hS6bu44ybB8/son+3p47tZDodK+PEc01YoC8J5Qzs9ErpsV6T8rdhFXwuhtGaa+
            xAgK7eZNYtNN0vL4GtHVdXCyUZABsZWcEdMGXVLizgXPX9/UktcTZe6wPCYDSLlV
            UuuXQkAKOkFxW6BFQVLp/S9gQVIJdownuyF9qFo+t2SB/BsI2nmKLB9lypzeP19/
            q++SAL6PMD7iLcT+DOB2Soq61Y87I0LIK5DhSxxIBzplJ/HTdtFnQ1RO2zZf7syc
            /nrAwc6Sh+So/gv/KE0mx1pd3ADveIo2KIjGmTf0RYxIVsh+p7bX4qM7N8/dFM2K
            /1jHaHGYDCsoumGFIstHvUOuNjyViFssGkJjh0UocgGNq9a4KH9az7tSDleEIhjH
            bbfNfYDvVkNIGuBJC6lyoRosCQ06qJIXJhA0CDUfAF2ilOgISj0Xi7P3x6Ph7Lb9
            kTpoXrVt63eKeYuhBhvUROT3S2EJ7Rqrj9taOPOP1nuhz4oDmuQqqbX90lkbdr1g
            /NAuzZV8HWSHGUieUYRYUbCUlzYvgWYKIIGX85r8I324zPPtpgx+I7NCtv/T6a/S
            XgFuyXe4Q2NfJy4N5JCtw5x/q89W9lxnDQPrBSMIXGFPH6qb483K4rHXb1OsA4Y2
            qSHQUhionijoOV3JJ1YBH7+U7uQdrOYoTpsU8fJz0CKQ/v01uNDJ49fdTDBhKjg=
            =oTkb
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
    name: console-secret
    namespace: minio-s3
type: Opaque
data:
    #ENC[AES256_GCM,data:ODx2T9CVowTmWsjFKUZiQDU0QWIz6YnSrd2SMUj96leEZNTp2VjKpqJcrmtaTMkizO+4dBKy3Rgp5McPruo/AMndoK/17tKb8ZN3jKy02g==,iv:99TwfGsoKRqBzOQ0S/HlMKqa/pnTRrAGXlUe8deHCbA=,tag:VJXwrjAErvgBVoIOFnahyQ==,type:comment]
    CONSOLE_PBKDF_PASSPHRASE: ENC[AES256_GCM,data:us6tVkffXRYkgCjQJkYb2gyhTKRvNI58X3YB0KhKnEPqtXbPvygWlPhy1+o=,iv:+Sgr9HKS/gErYcVO7H2QiBsem96Y254PEcJfYe9SrAo=,tag:+O9VCeKgTHkq45HjcYJ9Bg==,type:str]
    #ENC[AES256_GCM,data:fpjqgIvpUvBlREmXB+hroG5ah0zI7oWJAZs2V+JP/AKa9zTIqCUBC3GCQtjY56zYHcH2MgLbIANtQWRPC/ulBtTRiyKkCUHInA==,iv:Ip4QRVcrkFhgiNDkukMlbGBO4Gd6ke0uYtXZRo83LBg=,tag:8bvaFCPgNC7UpuZ27h6a5A==,type:comment]
    CONSOLE_PBKDF_SALT: ENC[AES256_GCM,data:aTgOam0Q5bKD/p/34GCyltpDY5uEM4n7oUYa7jX+srEnt8LB/qYftl1MDTA=,iv:qSjDGefeBOyQOlOybh62+cT5UEcDU/wNdXiADyZxROg=,tag:BVtqOiGtTbSf9KC8oRS+Rg==,type:str]
    #ENC[AES256_GCM,data:deUIYKR5hkjEoNFu5+XUlIhb7yALfPSV/W9LZGbFhwjqXk7nKCDJFOlB1GFxnbP2ga09TrQTmeopA2/dTLt411ElHQx+fFV0igRc1xcgZ20NdFjS3D/DY10R0BXHW3R8cjM/jSnY/w==,iv:ywVLgxy0BzXA7SARmfegrXzDylkm6J4etbqGxyYNDI8=,tag:GHjJp7Ow4JpR42xQH6QVVg==,type:comment]
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:L7iZ0E+UqUY=,iv:SYaQEPePa5QTZ0aADwV1f4o7UyNfJtZE8VFmfjp0P94=,tag:YXius65dazuG/WWj+jk91A==,type:str]
    #ENC[AES256_GCM,data:N7kj0SeLGweHyhSxhqlm5gTCiV2Yd/FUbU5M1aWTqJvTTNfUGWsdG0zwzXXjQ6vdGJPN+7V5aJXiHuyV6ioiFoSh19fMpv/ID4AkfEfNmgyKNsEvr1wDGbQaxSAHns5D0GRYWsoLGw==,iv:Oy8/DF3z16AXyLbwUwyWDJuPVFdqdeyCqqnpuLtKvMw=,tag:6SH5iD4AOtTutAVwW3HGjw==,type:comment]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:KitGFx4RjZyanWrmjNbo1E0/+qX9nvhhDS+olOl8FDk6dymKCkgzES1gkhE=,iv:0DK8cq82RABePDirOTvuPjW+dGHXn5cgbjkIYozqLbc=,tag:HbkjuKWBRVnCBBrL4+jj3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-14T18:49:37Z"
    mac: ENC[AES256_GCM,data:tggWCzBQRtFJoHX4rT7hNZsNGDVXc7koOh9OAJQ6Tfw8SoAZlj1GCOX8mWPWxdL4icbuHalbWM7aa3PWlGGzaCIEC0zBV7YUQYY5cwSp0jJW3AYfMDWjOLxk1K44n90Croou3gV+JHZKGz2PwNAXsnFfHaPksjI7Bns6yLRP7xg=,iv:lXAQUG2mg766rzEVg4CfZ1sLuQK7RSf+r0FsfvaDemA=,tag:l2pm6BEu2t1L4mep/ttlsw==,type:str]
    pgp:
        - created_at: "2021-05-14T18:49:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/AQ/+PTB0gzX3ArPloFzeNE1u4SseRo5KBQ0iVV/NCCUS+CmT
            36XeAOzeAe7ISIeiUmzzdsTSkBld9H3KEdP6m0o7GusRLyOaQSDzSBLc4DtGfBKD
            3hS6bu44ybB8/son+3p47tZDodK+PEc01YoC8J5Qzs9ErpsV6T8rdhFXwuhtGaa+
            xAgK7eZNYtNN0vL4GtHVdXCyUZABsZWcEdMGXVLizgXPX9/UktcTZe6wPCYDSLlV
            UuuXQkAKOkFxW6BFQVLp/S9gQVIJdownuyF9qFo+t2SB/BsI2nmKLB9lypzeP19/
            q++SAL6PMD7iLcT+DOB2Soq61Y87I0LIK5DhSxxIBzplJ/HTdtFnQ1RO2zZf7syc
            /nrAwc6Sh+So/gv/KE0mx1pd3ADveIo2KIjGmTf0RYxIVsh+p7bX4qM7N8/dFM2K
            /1jHaHGYDCsoumGFIstHvUOuNjyViFssGkJjh0UocgGNq9a4KH9az7tSDleEIhjH
            bbfNfYDvVkNIGuBJC6lyoRosCQ06qJIXJhA0CDUfAF2ilOgISj0Xi7P3x6Ph7Lb9
            kTpoXrVt63eKeYuhBhvUROT3S2EJ7Rqrj9taOPOP1nuhz4oDmuQqqbX90lkbdr1g
            /NAuzZV8HWSHGUieUYRYUbCUlzYvgWYKIIGX85r8I324zPPtpgx+I7NCtv/T6a/S
            XgFuyXe4Q2NfJy4N5JCtw5x/q89W9lxnDQPrBSMIXGFPH6qb483K4rHXb1OsA4Y2
            qSHQUhionijoOV3JJ1YBH7+U7uQdrOYoTpsU8fJz0CKQ/v01uNDJ49fdTDBhKjg=
            =oTkb
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
