apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-rancher-ingress
  namespace: cattle-system
spec:
  dnsNames:
    - rancher.bergmann.click
  secretName: tls-rancher-ingress
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
