apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |
    certificatesResolvers:
      inwx:
        acme:
          dnsChallenge:
            provider: inwx

