apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |
    global:
      checkNewVersion: true
      sendAnonymousUsage: true
    serversTransport:
      maxIdleConnsPerHost: 200
    entryPoints:
      traefik:
        address: ":9000/tcp"
      web:
        address: ":8000/tcp"
        http:
          redirections:
            entryPoint:
              to: ":443"
              scheme: "https"
      websecure:
        address: ":8443/tcp"
        http:
          tls: {}
    api: 
      dashboard: true
      insecure: true
    ping:
      entryPoint: "traefik"
      terminatingStatusCode: 503
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        ingressClass: traefik
    accessLog:
    log:
      level: INFO
    metrics:
      prometheus: {}
