= Bootstrap

This page describes how to setup the K3S cluster on the Raspberry Pi and how to connect to the cluster on my pc.

Thereafter xref:index.adoc#flux2[Flux2] should do the rest of the setup.

== Initial Setup

These commands are all executed on the local host. The first one reques ssh access to the raspberry Pi on IP 192.168.8.16.

* `k3sup install --ssh-key ~/.config/ssh-ident/identities/personal/id_ed25519 --host 192.168.8.16 --k3s-extra-args="--disable servicelb --disable traefik" --ip 192.168.8.16 --k3s-version=v1.21.0+k3s1 --local-path ~/.config/kube/config`
* `flux check --pre`
* `kubectl create namespace flux-system`
* get secret key file 'sops.gpg' from 1password
* `kubectl create secret generic sops-gpg -n flux-system --from-file sops.asc=sops.gpg`
* `kubectl apply --kustomize=./cluster/base/flux-system`

=== Flux

From here Flux takes control and configures the cluster.
This is done in the following stages:

. The last command of the initial setup installes (link:https://github.com/bergmann-it/homepi-cluster/blob/main/cluster/base/flux-system/gotk-components.yaml[gotk-components.yaml]) and configures (link:https://github.com/bergmann-it/homepi-cluster/blob/main/cluster/base/flux-system/gotk-sync.yaml[gotk-sync.yaml]) flux. It also installs the helm repositories.
. Thereafter flux will download the repository and start its deployment at the link:https://github.com/bergmann-it/homepi-cluster/tree/main/cluster/base[entrypoint].
. First it deploys the link:https://github.com/bergmann-it/homepi-cluster/tree/main/cluster/crds[CRDs] which are needed for the next steps.
. Then the link:https://github.com/bergmann-it/homepi-cluster/tree/main/cluster/core[core] components are deployed. See xref:core.adoc[core page] for details.
. Lastly all link:https://github.com/bergmann-it/homepi-cluster/tree/main/cluster/apps[applications] are deployed to the cluster.

== cleanup

If you want to start fresh call `+k3s-uninstall.sh+` on the Raspberry Pi.

