= General

Welcome to the documentation of my kubernetes cluster.

This cluster is running link:https://k3s.io[k3s] on the xref:hardware.adoc[hardware].

== Core components

=== Networking

The cluster uses link:https://traefik.io/[traefik] for networking.

link:https://metallb.universe.tf/[MetalLB] works with the xref:da::network.adoc[Router] via BGP to provide Adresses from the 192.168.8.32/27 range to the cluster.

=== Secrets

I manage my secrets with link:https://github.com/mozilla/sops[SOPS] as described in the link:https://toolkit.fluxcd.io/guides/mozilla-sops/[flux documentation about SOPS].

The public key and config file can be found in the link:https://github.com/bergmann-it/homepi-cluster/tree/main/cluster[cluster directory].

A backup of the private key is in 1password.

=== TLS

link:https://cert-manager.io/docs/[cert-manager] is configured to provide certificates for the services via LetsEncrypt.

== Automation emoji:robot_face[] 

The cluster is monitored by link:https://renovatebot.com[renovate bot].
The bot is configured with the link:https://github.com/bergmann-it/homepi-cluster/blob/main/.github/renovate.json5[config file] and manages a link:https://github.com/bergmann-it/homepi-cluster/issues/1[dashboard issue] with an overview of all open issues.
A list of renovate jobs can be found in the link:https://app.renovatebot.com/dashboard#github/bergmann-it/homepi-cluster[renovatebot dashboard].


