---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calinco
  namespace: calico-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://docs.projectcalico.org/charts
      chart: tigera-operator
      version: v3.21.3
      sourceRef:
        kind: HelmRepository
        name: calinco-charts
        namespace: flux-system
  values:
    #we define the installation later
    installation:
      enabled: false
