apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV6: 
      interface: eth0
    nodeAddressAutodetectionV4:
      interface: eth0
    ipPools:
      - cidr: 10.42.0.0/16
        encapsulation: None
      - cidr: fd53:f3c0:fefd::/48
        encapsulation: None
