---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: "192.168.8.32/27"
  BGP_ROUTER: "192.168.8.1"
  BGP_ASN: "64512"
  NODE_MASTER: "192.168.8.16"
  LB_INGRESS: "192.168.8.32"
  LB_UNIFI: "192.168.8.33"
