---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      version: 0.0.25
      sourceRef:
        kind: HelmRepository
        name: containeroo-charts
        namespace: flux-system
  values:
    storageClass:
      defaultClass: true
