---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16.2.5
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  removeOSDsIfOutAndSafeToRemove: false
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network:
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
    modules:
    - name: pg_autoscaler
      enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "homepi"
      devices:
      - name: "/dev/vg_rpi/ceph-bd"
  disruptionManagement:
    managePodBudgets: true
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
  healthCheck:
    livenessProbe:
      mgr:
        disabled: false
        probe:
          timeoutSeconds: 10
