---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.6
      sourceRef:
        kind: HelmRepository
        name: hass-charts
        namespace: flux-system
  values:
    service:
      port: 443
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: hass.bergmann.click
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - hass.bergmann.click
          secretName: hass-cert
