---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.44
      sourceRef:
        kind: HelmRepository
        name: hass-charts
        namespace: flux-system
  values:
    env:
      TZ: 'Europe/Berlin'
    persistence:
      enabled: true
      storageClass: "local-path"
    initContainers:
     - name: init-helios2n-cc
       image: alpine/git
       command: [ "/bin/sh", "-c" ]
       args:
       - |
         git clone https://github.com/bergmann-it/helios2n-hass.git /git/helios2n-hass
         cp -r /git/helios2n-hass/custom_components/helios2n/* /helios2n_cc
         chown -R 1000:1000 /helios2n_cc/*
       volumeMounts:
       - name: helios2n-cc
         mountPath: /helios2n_cc
    additionalVolumes:
     - name: helios2n-cc
       emptyDir: {}
    additionalMounts:
     - mountPath: /config/custom_components/helios2n
       name: helios2n-cc
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      hosts:
        - host: hass.bergmann.click
          paths:
            - path: /
              pathType: Prefix 
      tls:
        - hosts:
          - hass.bergmann.click
          secretName: hass-cert
