apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-zigstar
  namespace: default
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523"
    name: udev
