---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: akri
      version: 0.13.8
      sourceRef:
        kind: HelmRepository
        name: akri-charts
        namespace: flux-system
  values:
    kubernetesDistro: k3s
    udev:
      discovery:
        enabled: true
