apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |
    global:
      checkNewVersion: true
      sendAnonymousUsage: true
    serversTransport:
      maxIdleConnsPerHost: 200
      insecureSkipVerify: true
    entryPoints:
      mqtt:
        address: ":1883/tcp"
      mqtts:
        address: ":8883/tcp"
      openmqtts:
        address: ":8884/tcp"
      unificontroller:
        address: ":8080/tcp"
      unifidiscovery:
        address: ":10001/tcp"
      unifistun:
        address: ":3478/udp"
      unificaptive:
        address: ":8881/tcp"
      unificaptives:
        address: ":8844/tcp"
        http:
          tls: {}
      traefik:
        address: ":9000/tcp"
      web:
        address: ":8000/tcp"
        http:
          redirections:
            entryPoint:
              to: ":443"
              scheme: "https"
              priority: 10
      websecure:
        address: ":8443/tcp"
        http:
          tls: {}
    api: 
      dashboard: true
      insecure: true
    ping:
      entryPoint: "traefik"
      terminatingStatusCode: 503
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: true
      kubernetesIngress:
        allowEmptyServices: true
        allowExternalNameServices: true
    accessLog:
    log:
      level: INFO
    metrics:
      prometheus: {}
