apiVersion: v1
data:
    users: ENC[AES256_GCM,data:PEGutVm96S4z02haMb7UQl9F1gq6pZ8KHtTN/US8WXAlyY5rZ6FuzMGVjQ==,iv:wwB++lK9NPKdbiqgH4nsAEk7wF6zHbeRbXiHp5d33O4=,tag:VYbh+4RDM8QRSBNqOhcpWQ==,type:str]
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T19:55:21Z"
    mac: ENC[AES256_GCM,data:uJB0iHtFwQhnvl1Wyd67aw/LPPdiYT6wj7wpGxPoLV9o98NR8Q9m+PvjGxFQoPOEiyOjYwB9X8I7fS08ooirfQGitgwrCcLdrFUqyIjNevEUFnW7llGMsyH2lAgaQHkBY55AaTiilwlfNn/tM0FtD5X9/pJvkbmYfotWzYEeTYY=,iv:Atqf6s2zinJgwTE1M3fD6rQ1xOoqM/fN9GxeiRoNJbI=,tag:ZBNbt857bEKiDQvVMQu/xA==,type:str]
    pgp:
        - created_at: "2021-05-05T19:55:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/ARAAvVp+4hhzaGAAzkbkoUYmmbMTE2c2QsEMtcLZjhxxIjdW
            H53IUK+widA3rXRaqwj+ygPC/WrvYVAgvwLr7JDV371VtwPK2uGaHJ46wqL8qfDD
            RPrQJfaJ1F75vWJUc9nInLM+MrReFYueYyBsDh+LjX5+tczHph8epEqKcvQ4w2xJ
            MZNiiWFNpf80kd/DAwFN3AngCpVtBNmlb8i+iyCjb3DKEeL0MGwEYgVOY4Fr45bc
            YhtqzEqmbuQVpycieU88OwGhwJwKMhfCKlXN7lzsGq99HlZ4sE045ycEuqdfW7Li
            myIL3eTgCfT2JQ+ohUQHhtzZHAilWU7g5FhTEWdNAH2+/NKIkOcE97USV2Cgt/pc
            101JO5E5W8oqA1sZnrlpIfRbhoZOuAdA0wWJ0dUinfQhqf1A1hh7rv5CNS2/buQh
            0FjfndIr3/MMTWiVMKMMelgGamWWHD9kqzKhZyn5/4vQ4c6Bi3KPtou6o4Qd3Z4Q
            K5Ilp6ed3BG01FQepDB30ScnnMxNkgI6PHOynq52bciCpOHmuujKR2JPPJlTjo/j
            Z8WEMWQteVEFWTFgg6sW95J3RnrqKX0Hm4QEED+flbEuRUFjoW9HsxfIs4Zss0JL
            aT60Bcu9OKvUOFgsPM7X1WoAJ5LGgkrlY5ZTlW1gSY+1j2pOEHZavKVT0CYkb0jS
            XgEGvHY4NqHkSzfA7BlXqtR43+vkQ9tTUR+sUa8rgyY2mCXHiPn82sNYNKFUot2U
            /UF1Z5kUwMouS8nZ0saF3jDCKcohWGXSKuKAsxv0qMLK9AaPdq2k+ostbvlN3kQ=
            =pjjD
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
