apiVersion: v1
data:
    users: ENC[AES256_GCM,data:3WlHEfmqR/rzYDFhumkmhmE/XCQlGgfmz1Czq0M8un5FLN2p3m3iENVwng==,iv:GRImox++zhNnPJFYRdg8ACVpA9wUYmyf0NB8M8tURkY=,tag:cscDgQGvExl+0hH5061XwQ==,type:str]
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-25T19:36:01Z"
    mac: ENC[AES256_GCM,data:w2/Wz51nGJ9z1ePY7dtwRAZ1do3vSFHNn1uo0pV+mHhA9IiMlxQcgVGfKU4swSB3prIG/ao/WCNS7p6bfDFFgUNSsIhyMl3HTUUqFx0XIB197xYTgRHyyCBpGWXrQAtQqQyOpT5RyuFqMLbI1r+BxRMq+51FHgIU4dHeTXXgUUg=,iv:UNgItCVGvUCUG7pILyIl8F02A+ezcXM9OyYuWmw/Y0w=,tag:jGZ5etK8lleqcTnmBU61lg==,type:str]
    pgp:
        - created_at: "2021-04-25T19:36:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/ARAAzZ3zXperoWnURUc9nBvbZWYxb8CSHK5FJ5DotriF0Dgp
            G+sa6xugCa3hdneNxoVc4ZDOFeVwTi9sE3nP4mHMZZPr4sFEQZfrxs1/t8JHmgtS
            6b82XKmBAA30+NTjRVx1tqGi9C3IsLez/vAD9nQcyNrbWcN7EZPTZhS9hTtCtpW9
            OeQL7u9XCrEgDwOF+AN73fXhuwJ4XNqN4Xg1HeoDUDqMbi7dbrjLQ+3t/4T0BJex
            ImSKFCD/1WRE1FHZJubrPJc+y4FDtnccFb4jSI5SRMzOEeoGux20B38VZGqm7RSE
            9giNgFiyCCWOinZtSpiyd+q5UiNeLrDlE+XVkJdCBgvzf6ogUY+BoO0aJtAUjcji
            pRXZJRUNPxEV30LD+dDrMW+Yv9SuD6MrlDi/2Av8fiPphtGd5fLnY4Nx7KuObj+X
            FjbWw3RY2voBeu4Ypic8OpaWgM+xWgrBbPHJdz/BWhbgaFmRLacqnyv6bL4JLZX8
            Ryn+mglwDZIDvpQ9U32WW7LXDLyqLHBNjG5UgXVr2+nEeCoKXrDpV5BVSC1vtgic
            ACh4nEOLX2W/P2zTL5Dk6gYy2AUyA4TpRy/TTOxlyfcX+dIkFZ8Fo/qWqYxuuKIC
            jsBmwyNIl+6OItad0Q+IVexC8y3uret3Hy/5Y5iJsMQB1maMWB1hwBO53vBI4uLS
            XgEKlfRpIZdHiGSezfNzgT/TcM9Nz/n7zXzAXG8ILlp0dzbAQOjXkiI9xe2qOpdJ
            K5wLyN2fDeuqgoikrtpIF2JjufUNAFSi/ZxiQ7zO81e7Rsm6YAplHZBeayxgHVU=
            =jyVh
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
