---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
