---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raspberrymatic
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: raspberrymatic
      version: 3.81.5
      sourceRef:
        kind: HelmRepository
        name: raspberrymatic-charts
        namespace: flux-system
  values:
    persistence:
      data:
        enabled: true
        size: 256Mi
        accessMode: ReadWriteOnce
        storageClass: "local-path"
