apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.enc.yaml
- longhorn-middleware.yaml
- helm-release.yaml
patchesJson6902:
- target:
    version: storage.k8s.io/v1
    kind: StorageClass
    name: local-path
  patch: |-
    - op: replace
      path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
      value: "false"
