apiVersion: v1
stringData:
    users: ENC[AES256_GCM,data:Rcr5JxB4/WkmbNdoCDaa6r+pv8QwMnEHBzeHbDcsCy9HWpDXjvRPPRLhJw==,iv:JA+zSV7LhlbKz48efaJlUyHH7J12l1w8Exf5PB+bY1w=,tag:nCfsjoroCOSMy8OsFdODMg==,type:str]
kind: Secret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-25T20:42:28Z"
    mac: ENC[AES256_GCM,data:wGiLQMuEvA2Cl8NfES/8JkuqvgZS3/dkX2sIRO+tHM4K1TCOU8y/Oveh9dQrNWBmFtLbZuswvMX2rwvLBm0p3B6WPX69GgVy7rLgnVT2TisWjMAf45aCjnt0XIELFVY4nVIan0BVVA8xjjfBMZduhx+tH/9Xr2t8of/nXA1shaQ=,iv:Lnx6v2R+1DwYahCvi1I72RtxeE0lxyH4b+v5yDxvxYk=,tag:xaKpS8cLmRTpI7syhieEFw==,type:str]
    pgp:
        - created_at: "2021-04-25T20:42:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/AQ//dh/x+KKTopyCfRgVtYNPpm25+62+veukE4pKjPgNa59S
            vie2dty3hS3uGeV+cRNpRastPHz7v8mgpKGnxV1uh2rcr6vr9gS6NhcA0yA7+/ON
            bmDIdqrPmCgIDl7xsj98CGAgm/dNt6RarBt/dQbUoBR0IgkU84z4AkQSgwS99Wt8
            vjIH6hxz+vffelIdneuWZn20xq5V3Sj0l7WDB16LXDg/aqLtjiQqAASR07NUnS70
            AsJjR6wDc09xj9T5Fp17uR+6ZVPXI2mkYXJ/8SYeRGIZodocCTavxM9rGgmvZipu
            cwiqScRx1t/JH3D5+xw0rgNcfg7ADQZ9pkqeV5EbMhhhjnQXxnNaRpQslzboRzFE
            QZQKYHP42N5j+cxberYeZDRvv2Q/2dWIhhMGrRVtSFynJaGOopNqXhcJ9nzrRGUf
            Mi/VL/d1ogaKDx/QUZRHdhcjf6jDKn+rwKJCjjtSkb6iki3O0Sfeb2IBv6ui6vYQ
            FXy4vykKtTPdo9kVQX+RMuAocibCM4bxRaD2xQFyPUh5V3JJsGYNP8f7yvO/wylc
            ffhIptjhTmHT3qbLrnpIWHIq/2Sy2PrfMF43XW/LKOdKKBFXtuHvomy01kpkyf0O
            twZtTOUJg/6jweA26k3x4jO3fzGePe9x91FyybaKjgB2TI7BVUsGx9KGoPOSmDzS
            XAHbBj+8BHpDGgBGHKelYe60GNaQyPst9m7MYebcPtQrDz1W+VzMeYUrXpFUGpHX
            manVX6VCNe9UAfes3sz1kpmqD4T089WTiiUrdhgW2D5TsoHS1PY5MEJ3lJ/K
            =a+tk
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
