apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto-mqtt
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entrypoints:
    - mqtt
  rules:
    - match: HostSNI(`*`)
      services:
        - name: mosquitto
          port: 1883
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto-mqtts
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entrypoints:
    - mqtts
  rules:
    - match: HostSNI(`*`)
      services:
        - name: mosquitto
          port: 8883
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto-openmqtts
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entrypoints:
    - openmqtts
  rules:
    - match: HostSNI(`*`)
      services:
        - name: mosquitto
          port: 8884

