apiVersion: v1
data:
    token: ENC[AES256_GCM,data:rbG/tB6sahkv8YAknfoPWjqLi9dzRSaMK8WvLE7d+rMMIneFibALrmb1eAdiC1YPLxALgJqL3T8=,iv:09JtdWQ2SwP3ugUw7Vb3yeSw7SEgts5QdESz4Ou58+4=,tag:/Z3Pfb4rFOa2+KwfkVEGZg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-24T19:25:12Z"
    mac: ENC[AES256_GCM,data:EOqALUHk+M1Rl+w6gTdgFlwTSqOUpInNzeDc9Y7Yf/4+frAMwq7KPnUEFaqyEY4519IhqtutzYEbBng0mpHX4ZPrHfwWuUdlrSz0J1Q4i40kNuC7W4gZBdQUyhh+kN/vIuSM3bHE3m4M9OQQgiyjgqBIqp4jArrqXbyRREGS7JQ=,iv:f1sixZ+FK7cZHejhNwmKw5dmaq4ye99KWk0aFnG6E4c=,tag:yuY7r6H32IWCWeJr3v8Xww==,type:str]
    pgp:
        - created_at: "2021-04-24T19:25:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3E//P2MX8X/ARAAoaZ2SXLXNNT28O+TEiNw7r/C7NPUrYSSmgCIpc2WqqUk
            ckC1ynlU762mF50G3lxBbN7OLCz5CGlQ1c9SePEmuVeDJNPGOPcC/XUXoPrBQIxa
            CBMK00TPPxeLxNVR6ykbwhke9LiPJ2AwHyX+QAm7RWf3J9OSa4+EsYuweU7W48Qv
            7B7GDHCdLtldOJ2TYfoPEYXNPIqGZvUanWvFfzNvPC9Le1F/4DrFZtmxf6J69LJd
            /+41XHzoIvAqE3b25s2r9EzVLkKXg7GI287zJGW9YFll37L//RPne6aDJMobJPK5
            Cc8zTt2HqojbJCoz0DiStVopJRXMdDW0YTJZvkPY7F26hiuu23/MTOPoXB5mLLo7
            l/KiRJ+ACqnhbPWuQYt12CePrXax2kGQQjXhbjlEGX6U+KEaWaW1xj8mkPbA/qeT
            3yviCIH1JhIZn9PXPgdivuDbDCc9LqBAuyOdLhOWzGwWeX3jwnAy45SrUM8KbpKu
            JhmbzdIsrfBauN+PzVKZ88mCJ8VNxfDK8tU9OQEiWUVWlaukqBw8HTlFCYTFUG42
            AK6Qq5Ixik1fUJMk6tE1BU3kp0ukg05cOqwVBh56RqiVEJjQCU08iUWEgiejTTXy
            xZ6W8LuL+xT8OkUqkgkKG+lLHvwaKuYwU4M9CXYenY4TZPyiEy/BmFh4xluRj1jS
            XAEeET92AL3T4bsdQ0YBWLpBlUqYSUPSJ5ipxL/TYDDbG0o307xhB3X1nqCJBit3
            tai3wrQLHF0ErMZ94kUFvsD2LHmKTssFZYEHZ+zS9qaSn1MSMNC51DL9/YiP
            =LI44
            -----END PGP MESSAGE-----
          fp: 107F867893BC7485068D3EBFA4C6B059D1C55B1A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
