---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speech-to-phrase
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: speech-to-phrase
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: andrenarchy-charts
        namespace: flux-system
  values:
    env:
    - name: TZ
      value: 'Europe/Berlin'
    - name: HA_WEBSOCKET_URI
      value: 'wss://hass.bergmann.click/api/websocket'
    - name: HA_TOKEN
      valueFrom:
        secretKeyRef:
          name: speechtophrase-secret
          key: token
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: web, websecure, unificaptive, unificaptives
        hosts:
          - host: speechtophrase.bergmann.click
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - speechtophrase.bergmann.click
            secretName: speechtophrase-cert
