
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    nodeAddressAutodetectionV6: 
      interface: eth0
    nodeAddressAutodetectionV4:
      interface: eth0
    ipPools:
      - cidr: 10.42.0.0/16
        encapsulation: None
      - cidr: fd53:f3c0:fefd::/48
        encapsulation: None
---
# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: ${BGP_ASN}
  serviceExternalIPs:
  - cidr: "${METALLB_LB_RANGE_V4}"
  - cidr: "${METALLB_LB_RANGE_V6}"
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: edgerouter
spec:
  asNumber: ${BGP_ASN}
  peerIP: "${BGP_ROUTER}"
