---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: display-vol-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-dpl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: display
  template:
    metadata:
      labels:
        app: display
    spec:
      containers:
      - name: display
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: display-vol
          readOnly: True
      volumes:
      - name: display-vol
        persistentVolumeClaim:
          claimName: display-vol-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: display-update
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updatedisplay
            image: busybox:1.36
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date > /usr/share/nginx/html/index.html
            volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: display-vol
          restartPolicy: OnFailure
          volumes:
          - name: display-vol
            persistentVolumeClaim:
              claimName: display-vol-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: display-svc
  namespace: default
spec:
  selector:
    app: display
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: display
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  tls:
    - secretName: display-tls
      hosts:
        - display.bergmann.click
  rules:
  - host: display.bergmann.click
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: display-svc
              port:
                number: 80

