---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: display-vol-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-dpl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: display
  template:
    metadata:
      labels:
        app: display
    spec:
      containers:
      - name: display
        image: sibbl/hass-lovelace-kindle-screensaver:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /output
          name: display-vol
        env:
        - name: RUNTIME_NAMESPACE
          value: ""
        - name: HA_BASE_URL
          value: "https://hass.bergmann.click"
        - name: HA_SCREENSHOT_URL
          value: "/lovelace-tablet/kindle?kiosk"
        - name: CRON_JOB
          value: "* * * * *"
        - name: RENDERING_TIMEOUT
          value: 30000
        - name: RENDERING_DELAY
          value: 0
        - name: RENDERING_SCREEN_HEIGHT
          value: 800
        - name: RENDERING_SCREEN_WIDTH
          value: 600
        - name: GRAYSCALE_DEPTH
          value: 8
        - name: OUTPUT_PATH
          value: "/output/cover.png"
        - name: LANGUAGE
          value: "de"
        - name: ROTATION
          value: 0
        - name: SCALING
          value: 1
        - name: HA_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: display-token
              key: token
      volumes:
      - name: display-vol
        persistentVolumeClaim:
          claimName: display-vol-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: display-svc
  namespace: default
spec:
  selector:
    app: display
  ports:
    - protocol: TCP
      port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: display
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  tls:
    - secretName: display-tls
      hosts:
        - display.bergmann.click
  rules:
  - host: display.bergmann.click
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: display-svc
              port:
                number: 5000

