---
name: doku
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'docs/**'
    branches:
      - main
jobs:
  trigger-doku:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger doku update
        uses: peter-evans/repository-dispatch@v4
        with:
          token: '${{ secrets.TRIGGER_DOKU_TOKEN }}'
          repository: bergmann-it/doku
          event-type: update_doku
