---
name: doku
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'docs/**'
    branches:
      - main
jobs:
  trigger-doku:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger doku update
        run: |
          curl -sS -X POST https://api.github.com/repos/bergmann-it/doku/actions/workflows/deploy.yaml/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_DOKU_TOKEN }}" \
          --data '{"ref": "main"}'
