---
name: ci
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'docs/**'
    branches:
      - main
jobs:
  trigger-doku:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger doku update
        run: |
          curl -sS -X POST https://api.github.com/repos/cbergmann/doku/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.TRIGGER_DOKU_user }}:${{ secrets.TRIGGER_DOKU_SECRET }} \
          --data '{"event_type": "update_doku"}'
