---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-inwx
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager-webhook-inwx
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cbergmann-charts
        namespace: flux-system
