---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-inwx
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://smueller18.gitlab.io/helm-charts
      chart: cert-manager-webhook-inwx
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: smueller18-charts
        namespace: flux-system
